on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: FlexTFTP
      Test_Project_Path: Tests\Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

    - name: Upload release files
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "FlexTFTP/bin/Release/*.exe;FlexTFTP/bin/Release/*.txt"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
