on:
  workflow_dispatch:
  push:
    tags:
      - '*'

name: Create Release

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@20240405193535
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Create Release

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: FlexTFTP
      Test_Project_Path: Tests\Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test

    - name: Upload release files
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "FlexTFTP/bin/Release/*.exe;FlexTFTP/bin/Release/*.txt"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
